// Code generated by 'gorm.io/cmd/gorm'. DO NOT EDIT.

package twolevel

import (
	"gorm.io/cmd/gorm/field"
)

var S1 = struct {
	ID field.Number[int]
}{
	ID: field.Number[int]{}.WithColumn("id"),
}

var S3 = struct {
	ID field.Number[int]
}{
	ID: field.Number[int]{}.WithColumn("id"),
}
