// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package whitelist

import (
	"gorm.io/cli/gorm/field"
)

var S1 = struct {
	ID   field.Number[int]
	Name field.String
}{
	ID:   field.Number[int]{}.WithColumn("id"),
	Name: field.String{}.WithColumn("name"),
}
