// Code generated by 'gorm.io/cmd/gorm'. DO NOT EDIT.

package models

import (
	"gorm.io/cmd/gorm/field"
	"gorm.io/gorm"
)

var User = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	Name      field.String
	Age       field.Number[int]
	Role      field.String
	IsAdult   field.Bool
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Name:      field.String{}.WithColumn("name"),
	Age:       field.Number[int]{}.WithColumn("age"),
	Role:      field.String{}.WithColumn("role"),
	IsAdult:   field.Bool{}.WithColumn("is_adult"),
}
