// Code generated by 'gorm.io/cmd/gorm'. DO NOT EDIT.

package models

import (
	"database/sql"

	"gorm.io/cmd/gorm/examples"
	"gorm.io/cmd/gorm/examples/models"
	"gorm.io/cmd/gorm/field"
	"gorm.io/gorm"
)

var User = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	Name      field.String
	Age       field.Number[int]
	Birthday  field.Time
	Score     field.Field[sql.NullInt64]
	LastLogin field.Field[sql.NullTime]
	Account   field.Struct[models.Account]
	Pets      field.Slice[*models.Pet]
	Toys      field.Slice[models.Toy]
	CompanyID field.Number[int]
	Company   field.Struct[models.Company]
	ManagerID field.Number[uint]
	Manager   field.Struct[models.User]
	Team      field.Slice[models.User]
	Languages field.Slice[models.Language]
	Friends   field.Slice[*models.User]
	Role      field.String
	IsAdult   field.Bool
	Profile   examples.JSON
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Name:      field.String{}.WithColumn("name"),
	Age:       field.Number[int]{}.WithColumn("age"),
	Birthday:  field.Time{}.WithColumn("birthday"),
	Score:     field.Field[sql.NullInt64]{}.WithColumn("score"),
	LastLogin: field.Field[sql.NullTime]{}.WithColumn("last_login"),
	Account:   field.Struct[models.Account]{}.WithName("Account"),
	Pets:      field.Slice[*models.Pet]{}.WithName("Pets"),
	Toys:      field.Slice[models.Toy]{}.WithName("Toys"),
	CompanyID: field.Number[int]{}.WithColumn("company_id"),
	Company:   field.Struct[models.Company]{}.WithName("Company"),
	ManagerID: field.Number[uint]{}.WithColumn("manager_id"),
	Manager:   field.Struct[models.User]{}.WithName("Manager"),
	Team:      field.Slice[models.User]{}.WithName("Team"),
	Languages: field.Slice[models.Language]{}.WithName("Languages"),
	Friends:   field.Slice[*models.User]{}.WithName("Friends"),
	Role:      field.String{}.WithColumn("role"),
	IsAdult:   field.Bool{}.WithColumn("is_adult"),
	Profile:   examples.JSON{}.WithColumn("profile"),
}

var Account = struct {
	ID           field.Number[uint]
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field[gorm.DeletedAt]
	UserID       field.Field[sql.NullInt64]
	Number       field.String
	RewardPoints field.Field[sql.NullInt64]
	LastUsedAt   field.Field[sql.NullTime]
}{
	ID:           field.Number[uint]{}.WithColumn("id"),
	CreatedAt:    field.Time{}.WithColumn("created_at"),
	UpdatedAt:    field.Time{}.WithColumn("updated_at"),
	DeletedAt:    field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	UserID:       field.Field[sql.NullInt64]{}.WithColumn("user_id"),
	Number:       field.String{}.WithColumn("number"),
	RewardPoints: field.Field[sql.NullInt64]{}.WithColumn("reward_points"),
	LastUsedAt:   field.Field[sql.NullTime]{}.WithColumn("last_used_at"),
}

var Pet = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	UserID    field.Number[uint]
	Name      field.String
	Toy       field.Struct[models.Toy]
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	UserID:    field.Number[uint]{}.WithColumn("user_id"),
	Name:      field.String{}.WithColumn("name"),
	Toy:       field.Struct[models.Toy]{}.WithName("Toy"),
}

var Toy = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	Name      field.String
	OwnerID   field.Number[uint]
	OwnerType field.String
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Name:      field.String{}.WithColumn("name"),
	OwnerID:   field.Number[uint]{}.WithColumn("owner_id"),
	OwnerType: field.String{}.WithColumn("owner_type"),
}

var Company = struct {
	ID   field.Number[int]
	Name field.String
}{
	ID:   field.Number[int]{}.WithColumn("id"),
	Name: field.String{}.WithColumn("name"),
}

var Language = struct {
	Code field.String
	Name field.String
}{
	Code: field.String{}.WithColumn("code"),
	Name: field.String{}.WithColumn("name"),
}
