// Code generated by 'gorm.io/cmd/gorm'. DO NOT EDIT.

package examples

import (
	"context"
	"fmt"
	"strings"
	"time"

	"gorm.io/cmd/gorm/examples/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func Query[T any](db *gorm.DB, opts ...clause.Expression) _QueryInterface[T] {
	return _QueryImpl[T]{
		Interface: gorm.G[T](db, opts...),
	}
}

type _QueryInterface[T any] interface {
	gorm.ChainInterface[T]
	GetByID(ctx context.Context, id int) (T, error)
	FilterWithColumn(ctx context.Context, column string, value string) (T, error)
	QueryWith(ctx context.Context, user models.User) (T, error)
	UpdateInfo(ctx context.Context, user models.User, id int) error
	Filter(ctx context.Context, users []models.User) ([]T, error)
	FilterByNameAndAge(ctx context.Context, name string, age int) _QueryInterface[T]
	FilterWithTime(ctx context.Context, start time.Time, end time.Time) ([]T, error)
}

type _QueryImpl[T any] struct {
	gorm.Interface[T]
}

func (e _QueryImpl[T]) GetByID(ctx context.Context, id int) (T, error) {
	var sb strings.Builder
	params := make([]any, 0, 2)

	fmt.Fprint(&sb, "SELECT * FROM ? WHERE id=? AND name = \\\"@name\\\"", " ")
	params = append(params, clause.CurrentTable, id)

	var result T
	err := e.Raw(sb.String(), params...).Scan(ctx, &result)
	return result, err
}

func (e _QueryImpl[T]) FilterWithColumn(ctx context.Context, column string, value string) (T, error) {
	var sb strings.Builder
	params := make([]any, 0, 4)

	fmt.Fprint(&sb, "SELECT * FROM ? WHERE ?=?", " ")
	params = append(params, clause.CurrentTable, gorm.Expr("?", column), value)

	var result T
	err := e.Raw(sb.String(), params...).Scan(ctx, &result)
	return result, err
}

func (e _QueryImpl[T]) QueryWith(ctx context.Context, user models.User) (T, error) {
	var sb strings.Builder
	params := make([]any, 0, 2)

	fmt.Fprint(&sb, "SELECT * FROM users", " ")
	if user.ID > 0 {
		fmt.Fprint(&sb, "WHERE id=?", " ")
		params = append(params, user.ID)
	} else if user.Name != "" {
		fmt.Fprint(&sb, "WHERE username=?", " ")
		params = append(params, user.Name)
	}

	var result T
	err := e.Raw(sb.String(), params...).Scan(ctx, &result)
	return result, err
}

func (e _QueryImpl[T]) UpdateInfo(ctx context.Context, user models.User, id int) error {
	var sb strings.Builder
	params := make([]any, 0, 4)

	fmt.Fprint(&sb, "UPDATE ?", " ")
	params = append(params, clause.CurrentTable)
	{
		var tmp strings.Builder
		if user.Name != "" {
			fmt.Fprint(&tmp, "username=?,", " ")
			params = append(params, user.Name)
		}
		if user.Age > 0 {
			fmt.Fprint(&tmp, "age=?,", " ")
			params = append(params, user.Age)
		}
		if user.Age >= 18 {
			fmt.Fprint(&tmp, "is_adult=1", " ")
		} else {
			fmt.Fprint(&tmp, "is_adult=0", " ")
		}
		c := strings.TrimSpace(tmp.String())
		if c != "" {
			if strings.HasSuffix(c, ",") {
				c = strings.TrimSpace(strings.TrimRight(c, ","))
			}
			fmt.Fprint(&sb, "SET ")
			fmt.Fprint(&sb, c, " ")
		}
	}
	fmt.Fprint(&sb, "WHERE id=?", " ")
	params = append(params, id)

	return e.Exec(ctx, sb.String(), params...)
}

func (e _QueryImpl[T]) Filter(ctx context.Context, users []models.User) ([]T, error) {
	var sb strings.Builder
	params := make([]any, 0, 13)

	fmt.Fprint(&sb, "SELECT * FROM ?", " ")
	params = append(params, clause.CurrentTable)
	{
		var tmp strings.Builder
		for _, user := range users {
			if user.Name != "" && user.Age > 0 {
				fmt.Fprint(&tmp, "(username = ? AND age=? AND role LIKE concat(\\\"%\\\",?,\\\"%\\\")) OR", " ")
				params = append(params, user.Name, user.Age, user.Role)
			}
		}
		c := strings.TrimSpace(tmp.String())
		if c != "" {
			fmt.Fprint(&sb, "WHERE ")
			if len(c) >= 3 && strings.EqualFold(c[len(c)-3:], "AND") {
				c = strings.TrimSpace(c[:len(c)-3])
			} else if len(c) >= 2 && strings.EqualFold(c[len(c)-2:], "OR") {
				c = strings.TrimSpace(c[:len(c)-2])
			}
			fmt.Fprint(&sb, "WHERE ")
			fmt.Fprint(&sb, c, " ")
		}
	}

	var result []T
	err := e.Raw(sb.String(), params...).Scan(ctx, &result)
	return result, err
}

func (e _QueryImpl[T]) FilterByNameAndAge(ctx context.Context, name string, age int) _QueryInterface[T] {
	var sb strings.Builder
	params := make([]any, 0, 2)

	fmt.Fprint(&sb, "name=? AND age=?", " ")
	params = append(params, name, age)

	e.Where(sb.String(), params...)

	return e
}

func (e _QueryImpl[T]) FilterWithTime(ctx context.Context, start time.Time, end time.Time) ([]T, error) {
	var sb strings.Builder
	params := make([]any, 0, 3)

	fmt.Fprint(&sb, "SELECT * FROM ?", " ")
	params = append(params, clause.CurrentTable)
	{
		var tmp strings.Builder
		if !start.IsZero() {
			fmt.Fprint(&tmp, "created_time > ?", " ")
			params = append(params, start)
		}
		if !end.IsZero() {
			fmt.Fprint(&tmp, "AND created_time < ?", " ")
			params = append(params, end)
		}
		c := strings.TrimSpace(tmp.String())
		if c != "" {
			fmt.Fprint(&sb, "WHERE ")
			if len(c) >= 3 && strings.EqualFold(c[len(c)-3:], "AND") {
				c = strings.TrimSpace(c[:len(c)-3])
			} else if len(c) >= 2 && strings.EqualFold(c[len(c)-2:], "OR") {
				c = strings.TrimSpace(c[:len(c)-2])
			}
			fmt.Fprint(&sb, "WHERE ")
			fmt.Fprint(&sb, c, " ")
		}
	}

	var result []T
	err := e.Raw(sb.String(), params...).Scan(ctx, &result)
	return result, err
}
