// Code generated by 'gorm.io/cmd/gorm'. DO NOT EDIT.

package blacklist

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func I1[T any](db *gorm.DB, opts ...clause.Expression) _I1Interface[T] {
	return _I1Impl[T]{
		Interface: gorm.G[T](db, opts...),
	}
}

type _I1Interface[T any] interface {
	gorm.ChainInterface[T]
	ByID(ctx context.Context, id int) (T, error)
}

type _I1Impl[T any] struct {
	gorm.Interface[T]
}

func (e _I1Impl[T]) ByID(ctx context.Context, id int) (T, error) {
	var sb strings.Builder
	params := make([]any, 0, 2)

	sb.WriteString("SELECT * FROM ? WHERE id=?")
	params = append(params, clause.Table{Name: clause.CurrentTable}, id)

	var result T
	err := e.Raw(sb.String(), params...).Scan(ctx, &result)
	return result, err
}

func I2[T any](db *gorm.DB, opts ...clause.Expression) _I2Interface[T] {
	return _I2Impl[T]{
		Interface: gorm.G[T](db, opts...),
	}
}

type _I2Interface[T any] interface {
	gorm.ChainInterface[T]
	ByName(ctx context.Context, name string) (T, error)
}

type _I2Impl[T any] struct {
	gorm.Interface[T]
}

func (e _I2Impl[T]) ByName(ctx context.Context, name string) (T, error) {
	var sb strings.Builder
	params := make([]any, 0, 2)

	sb.WriteString("SELECT * FROM ? WHERE name=?")
	params = append(params, clause.Table{Name: clause.CurrentTable}, name)

	var result T
	err := e.Raw(sb.String(), params...).Scan(ctx, &result)
	return result, err
}
