// Code generated by 'gorm.io/cmd/gorm'. DO NOT EDIT.

package blacklist

import (
	"gorm.io/cmd/gorm/field"
)

var S1 = struct {
	ID   field.Number[int]
	Name field.String
}{
	ID:   field.Number[int]{}.WithColumn("id"),
	Name: field.String{}.WithColumn("name"),
}
